import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import AboutBlock, { AboutBlockInterface } from "../components/AboutBlock";
import Breadcrumbs from "../components/Breadcrumbs";
import TeamBlock, { TeamBlockInterface, TeamItemInterface } from "../components/TeamBlock";

interface Props {
  aboutBlock: AboutBlockInterface;
  teamBlock: TeamBlockInterface;
  team: TeamItemInterface[];
}

const About: NextPage<Props> = ({ aboutBlock, teamBlock, team }) => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumbs title="About us" />

      <AboutBlock aboutBlock={aboutBlock} />

      <TeamBlock teamBlock={teamBlock} team={team} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const aboutBlockRes = await fetch("http://localhost:5001/about_block");
  const aboutBlock: AboutBlockInterface = await aboutBlockRes.json();

  const teamBlockRes = await fetch("http://localhost:5001/team_block");
  const teamBlock: TeamBlockInterface = await teamBlockRes.json();

  const teamRes = await fetch("http://localhost:5001/team");
  const team: TeamItemInterface[] = await teamRes.json();

  return {
    props: {
      aboutBlock,
      teamBlock,
      team,
    },
  };
};

export default About;
