import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Breadcrumbs from "../components/Breadcrumbs";
import MenuBlock, { MenuBlockInterface, MenuItemInterface } from "../components/MenuBlock";

interface Props {
  menuBlock: MenuBlockInterface;
  menu: MenuItemInterface[];
}

const Menu: NextPage<Props> = ({ menu, menuBlock }) => {
  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumbs title="Menu" />

      <MenuBlock menuBlock={menuBlock} menu={menu} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const menuBlockRes = await fetch("http://localhost:5001/menu_block");
  const menuBlock: MenuBlockInterface = await menuBlockRes.json();

  const menuRes = await fetch("http://localhost:5001/menu");
  const menu: MenuItemInterface[] = await menuRes.json();

  return {
    props: {
      menuBlock,
      menu,
    },
  };
};

export default Menu;
