import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Breadcrumbs from "../components/Breadcrumbs";
import { MenuItemInterface } from "../components/MenuBlock";

interface Props {
  menu: MenuItemInterface[] | null;
}

const Search: NextPage<Props> = ({ menu }) => {
  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumbs title="Search" />

      <div className="py-5">
        <div className="container">
          <div className="row g-4">
            {menu && menu.length > 0 ? (
              menu.map(menuItem => (
                <div key={menuItem.id} className="col-lg-6">
                  <div className="d-flex align-items-center">
                    <img
                      className="flex-shrink-0 img-fluid rounded"
                      src={menuItem.image}
                      alt=""
                      style={{ width: "80px" }}
                    />
                    <div className="w-100 d-flex flex-column text-start ps-4">
                      <h5 className="d-flex justify-content-between border-bottom pb-2">
                        <span>{menuItem.name}</span>
                        <span className="text-primary">${menuItem.price}</span>
                      </h5>
                      <small className="fst-italic">{menuItem.description}</small>
                    </div>
                  </div>
                </div>
              ))
            ) : (
              <p>There are no results with your search... please try searching for menu items.</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  let resMenu,
    menu: MenuItemInterface[] | null = null;

  const searchQuery = query?.q;

  // you can search by q like this
  // GET /menu?q=text

  if (searchQuery) {
    resMenu = await fetch(`http://localhost:5001/menu?&q=${searchQuery}`);
    menu = await resMenu.json();
  }

  return {
    props: {
      menu,
    },
  };
};

export default Search;
